apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  # namespace: golden-wings # Optional: specify namespace
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
  clusterIP: None # Headless service for StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  # namespace: golden-wings # Optional: specify namespace
spec:
  serviceName: "mongo-service"
  replicas: 1 # Start with 1, can be scaled later
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        # Optional: Mount credentials if using MongoDB auth within the container
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: MONGO_INITDB_ROOT_USERNAME
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: MONGO_INITDB_ROOT_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ] # Suitable for single node DB on most cloud providers
      resources:
        requests:
          storage: 5Gi # Adjust size as needed
      # storageClassName: "your-storage-class" # Optional: Specify if not using default
